//Multi-Stage_Pipeline
pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Builiding'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying'
            }
        }
    }
}
