//Multi-Stage_Pipeline_on_windows/Jenkinsfile
pipeline {
    agent { label 'windows' }
    stages {
        stage('Build') {
            steps { echo 'Building...' }
        }
        stage('Test') {
            steps { echo 'Testing...' }
        }
        stage('Deploy') {
            steps { echo 'Deploying...' }
        }
    }
}