pipeline {
    agent any
    
     parameters {
        string(name: 'USERNAME', defaultValue: 'guest', description: 'Enter your username')
        booleanParam(name: 'DEPLOY', defaultValue: false, description: 'Deploy after build?')
        choice(name: 'ENVIRONMENT', choices: ['dev', 'staging', 'prod'], description: 'Select environment')
    }

    stages {
        stage('String params') {
            steps {
                script{
                    echo "Username: ${params.USERNAME}" 
                    echo "Env: ${params.ENVIRONMENT}"
                    echo "DEPLOY: ${env.DEPLOY}"
                }
            }
        }
    }
}
